[package]
name = "rdp-screenshot"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "Basic RDP screenshot CLI based on IronRDP"
readme = "README.md"
license = "Apache-2.0 OR MIT"
keywords = ["rdp", "screenshot", "remote-desktop"]
categories = ["command-line-utilities"]
repository = "https://github.com/Wazzaps/rdp-screenshot"

[dependencies]
anyhow = "1.0.101"
image = { version = "0.25.9", default-features = false, features = ["png"] }
ironrdp = { version = "0.14.0", features = [
    "session",
    "connector",
    "graphics",
] }
ironrdp-blocking = "0.8.0"
ironrdp-graphics = "0.7.0"
ironrdp-pdu = "0.7.0"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
sspi = { version = "0.18.7", features = ["network_client"] }
tokio-rustls = "0.26.4"
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
x509-cert = { version = "0.2.5", default-features = false, features = ["std"] }
