[package]
name = "rdp-screenshot"
version = "0.3.1"
edition = "2024"
rust-version = "1.88"
description = "Basic RDP screenshot CLI based on IronRDP"
readme = "README.md"
license = "Apache-2.0 OR MIT"
keywords = ["rdp", "screenshot", "remote-desktop"]
categories = ["command-line-utilities"]
repository = "https://github.com/Wazzaps/rdp-screenshot"

[dependencies]
anyhow = "1.0.101"
image = { version = "0.25.9", default-features = false, features = [
    "png",
    "jpeg",
] }
ironrdp = { git = "https://github.com/Devolutions/IronRDP", rev = "a6b41093ce4ece081d2538c157f6bc547c3b2607", features = [
    "session",
    "connector",
    "graphics",
] }
ironrdp-blocking = { git = "https://github.com/Devolutions/IronRDP", rev = "a6b41093ce4ece081d2538c157f6bc547c3b2607" }
ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "a6b41093ce4ece081d2538c157f6bc547c3b2607" }
ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "a6b41093ce4ece081d2538c157f6bc547c3b2607" }
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
sspi = { version = "0.18.7", features = ["network_client"] }
tokio-rustls = "0.26.4"
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
x509-cert = { version = "0.2.5", default-features = false, features = ["std"] }
